// Copyright 2018-2025 the Deno authors. MIT license.

/**
 * Don't modify this file manually.
 *
 * This file is auto-generated by the build script, modify `data.rs` instead.
 */

export const unstableIds = {
  broadcastChannel: 1,
  cron: 3,
  ffi: 5,
  fs: 6,
  http: 7,
  kv: 8,
  loaderApi: 10,
  net: 12,
  noLegacyAbort: 13,
  nodeGlobals: 14,
  otel: 16,
  process: 17,
  temporal: 19,
  unsafeProto: 20,
  vsock: 21,
  webgpu: 22,
  workerOptions: 23,
};
